targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/src/*/domain/models/**
      source_gen:combining_builder:
        generate_for:
          - lib/src/*/domain/models/**
      freezed:
        generate_for:
          - lib/src/*/domain/models/**
