# Eduplanner web app

services:
  eduplanner:
    env_file:
      - stack.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MOODLE_ENDPOINT: ${MOODLE_ENDPOINT}
        LB_PLANNER_ENDPOINT: ${LB_PLANNER_ENDPOINT}
        REFRESH_INTERVAL: ${REFRESH_INTERVAL}
        IMPORTANT_REFRESH_INTERVAL: ${IMPORTANT_REFRESH_INTERVAL}
        LESS_IMPORTANT_REFRESH_INTERVAL: ${LESS_IMPORTANT_REFRESH_INTERVAL}
        SENTRY_DSN: ${SENTRY_DSN}
        APP_NAME: ${APP_NAME}
        MAJOR_VERSION: ${MAJOR_VERSION}
        MINOR_VERSION: ${MINOR_VERSION}
        PATCH_VERSION: ${PATCH_VERSION}
        BUILD_NUMBER: ${BUILD_NUMBER}
        BUILD_CHANNEL: ${BUILD_CHANNEL}
        RELEASE_DATE: ${RELEASE_DATE}
        PATCH_NOTES: ${PATCH_NOTES}
        POSTHOG_API_KEY: ${POSTHOG_API_KEY}
        POSTHOG_HOST: ${POSTHOG_HOST}
        PRIVACY_POLICY_URL: ${PRIVACY_POLICY_URL}
        ECHIDNA_CLIENT_KEY: ${ECHIDNA_CLIENT_KEY}
        ECHIDNA_CLIENT_ID: ${ECHIDNA_CLIENT_ID}
        ECHIDNA_HOST: ${ECHIDNA_HOST}
        CALENDAR_PLAN_FEATURE_ID: ${CALENDAR_PLAN_FEATURE_ID}
    ports:
      - "${PORT-8080}:80"