# Eduplanner web app

services:
  eduplanner:
    env_file:
      - stack.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        BASE_HREF: ${BASE_HREF}
    ports:
      - "${PORT-8080}:80"
